version: '3.9'

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 54320:5432
    environment:
      # - POSTGRES_HOST=localhost
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - minhaRede
    # network_mode: bridge
  app:
    build: .
    container_name: rentx
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    networks:
      - minhaRede
    # network_mode: bridge

networks:
  minhaRede:
    driver: bridge
    # group: localRede

volumes:
  pgdata:
    driver: local
